//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações a este ficheiro poderão provocar um comportamento incorrecto e perder-se-ão se
//     o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCPFavThingsLib.ErrorResources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LCPFavThingsLib.ErrorResources.ErrorResources", typeof(ErrorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Category.
        /// </summary>
        public static string EMCategory {
            get {
                return ResourceManager.GetString("EMCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Company.
        /// </summary>
        public static string EMCompany {
            get {
                return ResourceManager.GetString("EMCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write or upload something in the field Cover.
        /// </summary>
        public static string EMCover {
            get {
                return ResourceManager.GetString("EMCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Date Release.
        /// </summary>
        public static string EMDateRelease {
            get {
                return ResourceManager.GetString("EMDateRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Description.
        /// </summary>
        public static string EMDesc {
            get {
                return ResourceManager.GetString("EMDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Duration.
        /// </summary>
        public static string EMDuration {
            get {
                return ResourceManager.GetString("EMDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This field only accepts positive numbers!.
        /// </summary>
        public static string EMDurationVal {
            get {
                return ResourceManager.GetString("EMDurationVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Genre.
        /// </summary>
        public static string EMGenre {
            get {
                return ResourceManager.GetString("EMGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Language.
        /// </summary>
        public static string EMLanguage {
            get {
                return ResourceManager.GetString("EMLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Password.
        /// </summary>
        public static string EMPassword {
            get {
                return ResourceManager.GetString("EMPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Publisher.
        /// </summary>
        public static string EMPublisher {
            get {
                return ResourceManager.GetString("EMPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Query Command.
        /// </summary>
        public static string EMQryCMD {
            get {
                return ResourceManager.GetString("EMQryCMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Rating.
        /// </summary>
        public static string EMRating {
            get {
                return ResourceManager.GetString("EMRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value should be less than or equal to 10.0.
        /// </summary>
        public static string EMRatingVal {
            get {
                return ResourceManager.GetString("EMRatingVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Title.
        /// </summary>
        public static string EMTitle {
            get {
                return ResourceManager.GetString("EMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Total Seasons.
        /// </summary>
        public static string EMTotalSeasons {
            get {
                return ResourceManager.GetString("EMTotalSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The value should be less than or equal to 50.
        /// </summary>
        public static string EMTotalSeasonsVal {
            get {
                return ResourceManager.GetString("EMTotalSeasonsVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please write something in the field Username.
        /// </summary>
        public static string EMUsername {
            get {
                return ResourceManager.GetString("EMUsername", resourceCulture);
            }
        }
    }
}
