// <auto-generated />
using System;
using LCPFavThingsWApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LCPFavThingsWApi.Migrations.SqlServerMigrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LCPFavThingsWApi.Models.Games", b =>
                {
                    b.Property<int?>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GameId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("GameId"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DateRelease")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DescT")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LangT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Rating")
                        .IsRequired()
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("GameId");

                    b.ToTable("Games", (string)null);

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Category = "Games",
                            Company = "Rockstar North",
                            Cover = "gtaiv.jpg",
                            DateRelease = "2008-04-28T00:00:00",
                            DescT = "GTA IV",
                            Genre = "Action,Adventure",
                            LangT = "English",
                            Publisher = "Rockstar Games",
                            Rating = 8m,
                            Title = "GTA IV"
                        });
                });

            modelBuilder.Entity("LCPFavThingsWApi.Models.Movies", b =>
                {
                    b.Property<int?>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MovieId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("MovieId"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DescT")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)");

                    b.Property<int?>("Duration")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LangT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Rating")
                        .IsRequired()
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Movies",
                            Company = "Paramount",
                            Cover = "ff8.jpg",
                            DescT = "The Fast and Furious 8",
                            Duration = 150,
                            Genre = "Action",
                            LangT = "English",
                            Rating = 9m,
                            Title = "The Fast and Furious 8"
                        });
                });

            modelBuilder.Entity("LCPFavThingsWApi.Models.TVSeries", b =>
                {
                    b.Property<int?>("TVSerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TVSerieId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TVSerieId"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DescT")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)");

                    b.Property<int?>("Duration")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LangT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Rating")
                        .IsRequired()
                        .HasColumnType("decimal(2,1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("TotalSeasons")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("TVSerieId");

                    b.ToTable("TVSeries", (string)null);

                    b.HasData(
                        new
                        {
                            TVSerieId = 1,
                            Category = "TV Series",
                            Company = "AMC,FOX",
                            Cover = "ftwd.jpg",
                            DescT = "FTWD",
                            Duration = 45,
                            Genre = "Action,Adventure",
                            LangT = "English",
                            Rating = 9m,
                            Title = "Fear The Walking Dead",
                            TotalSeasons = 8
                        },
                        new
                        {
                            TVSerieId = 2,
                            Category = "TV Series",
                            Company = "CW,RTP1,AXN",
                            Cover = "theflash.jpg",
                            DescT = "The Flash",
                            Duration = 45,
                            Genre = "Action,Adventure",
                            LangT = "English",
                            Rating = 8m,
                            Title = "The Flash",
                            TotalSeasons = 8
                        });
                });

            modelBuilder.Entity("LCPFavThingsWApi.Models.UserAuth", b =>
                {
                    b.Property<int?>("UserAuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserAuthId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UserAuthId"), 1L, 1);

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)");

                    b.Property<int?>("RoleT")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserAuthId");

                    b.ToTable("UserAuth", (string)null);

                    b.HasData(
                        new
                        {
                            UserAuthId = 1,
                            Avatar = "guest.jpg",
                            Password = "$2a$11$ebRZ9Bt7vq1BzaEUkIwdVeoyvsEkfcPdlqgd3JUNsR5zDZy15qjJm",
                            RoleT = 1,
                            UserId = 1,
                            Username = "guest"
                        },
                        new
                        {
                            UserAuthId = 2,
                            Avatar = "theflash.jpg",
                            Password = "$2a$11$l64F1SOO4gNRFjaXnNP1rubdOP/cYubPSjOUaw8x5bsBdat/NFfmy",
                            RoleT = 3,
                            UserId = 2,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("LCPFavThingsWApi.Models.Users", b =>
                {
                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UserId"), 1L, 1);

                    b.Property<string>("About")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Cover")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DateAccountCreated")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateBirthday")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordT")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("Pin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Pin");

                    b.Property<int?>("RoleT")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            About = "Guest is cool guy!",
                            Avatar = "guest.jpg",
                            Cover = "c_guest.jpg",
                            DateAccountCreated = new DateTime(2022, 7, 14, 15, 26, 50, 610, DateTimeKind.Utc).AddTicks(7829),
                            DateBirthday = new DateTime(1995, 5, 2, 23, 0, 0, 0, DateTimeKind.Utc),
                            Email = "guest@localhost.loc",
                            FirstName = "Guest",
                            LastName = "Convidado",
                            PasswordT = "$2a$11$2SERCjSvNPvsIDomsbzZguKvHQsAn2EcVUbv.Ah3X06cG22oejjoG",
                            Pin = "$2a$11$.9Kq/UPB8/qJL/zpYSYHJuB5DHtt3v0QWEoSM9WY8lQ3e.NIWO2B2",
                            RoleT = 1,
                            Username = "guest"
                        },
                        new
                        {
                            UserId = 2,
                            About = "Admin is cool guy!",
                            Avatar = "theflash.jpg",
                            Cover = "theflash.jpg",
                            DateAccountCreated = new DateTime(2022, 7, 14, 15, 26, 50, 953, DateTimeKind.Utc).AddTicks(1599),
                            DateBirthday = new DateTime(1995, 6, 3, 23, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@localhost.loc",
                            FirstName = "Admin",
                            LastName = "Admin",
                            PasswordT = "$2a$11$b2D3E7wwP95.jDUH95mHpO529hnicD9.ndGky7sxcCL9m60G5f9/W",
                            Pin = "$2a$11$zaQwe3ZP6wA4M.yy0BfJteGxLaIWj6d83JIfEbv3TL2OLo7QtykaW",
                            RoleT = 3,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("LCPFavThingsWApi.SecurityApi.JWT.UserToken", b =>
                {
                    b.Property<int?>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TokenId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("TokenId"), 1L, 1);

                    b.Property<string>("AccessToken")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Authenticated")
                        .HasColumnType("int")
                        .HasColumnName("Authenticated");

                    b.Property<string>("Created")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Expiration")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("TokenId");

                    b.ToTable("UserToken", (string)null);

                    b.HasData(
                        new
                        {
                            TokenId = 1,
                            AccessToken = "eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ",
                            Authenticated = 1,
                            Created = "2022-07-14T16:21:00",
                            Expiration = "2022-07-14T17:21:00",
                            Message = "OK",
                            UserId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
